# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
      if: ${{ matrix.node-version == '18.x' }}
    - run: npm run compile --if-present
    - run: npm test
    - name: Test Report
      uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203 # v1
      continue-on-error: true
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests      # Name of the check run which will be created
        path: junit.xml       # Path to test results
        reporter: jest-junit  # Format of test results
        fail-on-error: 'false'
    - uses: codecov/codecov-action@894ff025c7b54547a9a2a1e9f228beae737ad3c2 # v3.1.3
      name: Upload Coverage Results
      if: ${{ matrix.node-version == '18.x' }}
    - run: mv junit.xml amt-explorer-unit.xml
    - name: Upload JEST Results
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: amt-explorer-unit
        path: amt-explorer-unit.xml