# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      if: ${{ matrix.node-version == '18.x' }}
    - run: npm run compile --if-present
    - run: npm test
    - name: Test Report
      uses: dorny/test-reporter@e9fa2f582c0ebbe2e263fd18fad744d52e0b0203 # v1
      continue-on-error: true
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: JEST Tests      # Name of the check run which will be created
        path: junit.xml       # Path to test results
        reporter: jest-junit  # Format of test results
        fail-on-error: 'false'
    - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
      name: Upload Coverage Results
      if: ${{ matrix.node-version == '18.x' }}
    - run: mv junit.xml amt-explorer-unit.xml
    - name: Upload JEST Results
      uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
      with:
        name: amt-explorer-unit
        path: amt-explorer-unit.xml