# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run lint
      if: ${{ matrix.node-version == '16.x' }}
    - run: npm run compile --if-present
    - run: npm test
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      continue-on-error: true
      with:
        name: JEST Tests      # Name of the check run which will be created
        path: junit.xml       # Path to test results
        reporter: jest-junit  # Format of test results
        fail-on-error: 'false'
    - uses: codecov/codecov-action@v1.0.14
      name: Upload Coverage Results
      if: ${{ matrix.node-version == '16.x' }}
    - run: mv junit.xml amt-explorer-unit.xml
    - name: Upload JEST Results
      uses: actions/upload-artifact@v3
      with:
        name: amt-explorer-unit
        path: amt-explorer-unit.xml